version: '3'

services:
  mysql-standalone:
    image: mysql:5.6
    container_name: mysql-standalone
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mysqldemo
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  springboot-mysql:
    build: .
    image: kevpin/springboot-mysql
    ports:
      - 8086:8086
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/mysqldemo
    depends_on:
      - mysql-standalone
    extra_hosts:
      - host.docker.internal:host-gateway